Project1VS/force-app/main/default/objects/Realm__c/Realm__c.object-meta.xml
<CustomObject>
    <label>Realm</label>
    <nameField>
        <label>Realm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/objects/Realm__c/fields/Includes_States__c.field-meta.xml
<CustomField>
    <fullName>Includes_States__c</fullName>
    <label>Includes States</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

Project1VS/force-app/main/default/objects/Region__c/fields/Realm__c.field-meta.xml
<CustomField>
    <fullName>Realm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Realm</label>
    <referenceTo>Realm__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/classes/regionTriggerTest.cls
@isTest
public class regionTriggerTest {

    @isTest
    static void misaligned() {
        Realm__c realm = new Realm__c(Name='Realm', includes_states__c='New York');
        insert realm;
        Region__c region = new Region__c(Name='Reggie', realm__c=realm.Id, states__c='California');
        try {
        	insert region;
        } catch(DmlException d) {
            system.assert(true);
        }
    }
    
}