Project1VS/force-app/main/default/objects/Realm__c/Realm__c.object-meta.xml
<CustomObject>
    <label>Realm</label>
    <nameField>
        <label>Realm Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Realms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/objects/Realm__c/fields/Includes_States__c.field-meta.xml
<CustomField>
    <fullName>Includes_States__c</fullName>
    <label>Includes States</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>States</valueSetName>
    </valueSet>
</CustomField>

Project1VS/force-app/main/default/objects/Region__c/fields/Realm__c.field-meta.xml
<CustomField>
    <fullName>Realm__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Realm</label>
    <referenceTo>Realm__c</referenceTo>
    <relationshipLabel>Regions</relationshipLabel>
    <relationshipName>Regions</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/classes/regionTriggerHandler.cls
public class regionTriggerHandler {
    
    public static void checkStates(List<Region__c> regions) {
        String states = '';
        String regionstate = '';
        List<Id> realmIDs = new List<Id>();
        List<Realm__c> realms = new List<Realm__c>();
        for (Region__c reg : regions) {
            regionstate = reg.states__c;
            realmIDs.add(reg.Realm__c);
        }
        realms = [SELECT name, includes_states__c, id FROM realm__c WHERE id IN : realmIDs];
        for (Region__c reg : regions) {
            for (Realm__c relm : realms) {
                if (reg.realm__c == relm.id) {
                    states = relm.includes_states__c;
                    regionstate = reg.States__c;
                    if (!states.contains(regionstate)) {
                        reg.addError('This region must be in a state within the jurisdiction of this realm.');
                    }
                }
            }
        }
    }
    
}