Project1VS/force-app/main/default/objects/Character__c/Character__c.object-meta.xml
<CustomObject>
    <label>Character</label>
    <nameField>
        <label>Character Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Characters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/objects/Character__c/fields/Class__c.field-meta.xml
<CustomField>
    <fullName>Class__c</fullName>
    <label>Class</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

Project1VS/force-app/main/default/objects/Character__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>Characters</relationshipLabel>
    <relationshipName>Characters</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/Character__c/fields/Race__c.field-meta.xml
<CustomField>
    <fullName>Race__c</fullName>
    <label>Race</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Project1VS/force-app/main/default/objects/Character__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Characters</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/Party__c/Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/classes/partyPageTest.cls
@isTest
public class partyPageTest {
	
    @isTest
    static void testParties() {
            
        User uu = TestUtil.CreateTestUser();
        
        System.runAs(uu) {
        
            PageReference testPage = Page.partyPage;
            partyPageController ppc = new partyPageController();
            ptyPgExtender ppe = new ptyPgExtender(ppc);
            
            Test.setCurrentPage(testPage);
            
            //Create a new party and insert it into the database
            Party__c newParty = new Party__c(name='The Testers');
            insert newParty;
        
            //Select the party and make it the selectedParty
            ppe.selectedParty = newParty.Id;
            
            //Create a new character and insert that into the database
            Character__c Grog = new Character__c(name='Grog', race__c='Orc', class__c='Barbarian', party__c=newParty.id, user__c=uu.id);
            insert Grog;
            
            //Query for the character in the party
            ppe.getChars();
        	system.assert(ppe.getChars()[0]==Grog);
        
            
        }
    }
    
}