Project1VS/force-app/main/default/objects/DnDCampaign__c/DnDCampaign__c.object-meta.xml
<CustomObject>
    <label>DnDCampaign</label>
    <nameField>
        <displayFormat>DnDCampaign-{00000}</displayFormat>
        <label>DnDCampaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DnDCampaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/objects/DnDCampaign__c/fields/Dungeon_Master__c.field-meta.xml
<CustomField>
    <fullName>Dungeon_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dungeon Master</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>User.UserRole.Name</field>
            <operation>equals</operation>
            <value>Dungeon_Master</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>DnDCampaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/DnDCampaign__c/fields/Party__c.field-meta.xml
<CustomField>
    <fullName>Party__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Party</label>
    <referenceTo>Party__c</referenceTo>
    <relationshipLabel>DnDCampaigns</relationshipLabel>
    <relationshipName>DnDCampaigns</relationshipName>
    <type>Lookup</type>
</CustomField>

Project1VS/force-app/main/default/objects/DnDCampaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Idle</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1VS/force-app/main/default/objects/Party__c/Party__c.object-meta.xml
<CustomObject>
    <label>Party</label>
    <nameField>
        <label>Party Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/classes/DndCampaignController.cls
public class DndCampaignController {
    public DndCampaignController(){}
    public List<DnDCampaign__c> campList {get;set;}
    public DnDCampaign__c curCamp{get; set;}
    public DndCampaignController(ApexPages.StandardController sc){
        campList = [SELECT Name, Id from DnDCampaign__c];
        curCamp = new DnDCampaign__c();
   
        curCamp = [SELECT Id, Name, Dungeon_Master__c, Party__c, Status__c From DnDCampaign__c Where Status__c = 'In Progress'];
    }
    
    public PageReference GoToParty(){
         PageReference p = new PageReference('/apex/partyPage');
       	 p.setRedirect(true);
        return p; 
    }
}