Project1VS/force-app/main/default/objects/DnDCampaign__c/DnDCampaign__c.object-meta.xml
<CustomObject>
    <label>DnDCampaign</label>
    <nameField>
        <displayFormat>DnDCampaign-{00000}</displayFormat>
        <label>DnDCampaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DnDCampaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Project1VS/force-app/main/default/objects/DnDCampaign__c/fields/Campaign_Name__c.field-meta.xml
<CustomField>
    <fullName>Campaign_Name__c</fullName>
    <label>Campaign Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Project1VS/force-app/main/default/objects/DnDCampaign__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Idle</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Finished</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Project1VS/force-app/main/default/classes/DndCampaingTestClass.cls
@isTest 
private class DndCampaingTestClass {

 	@isTest static void myTest() {
        DnDCampaign__c reco = new DnDCampaign__c();
               reco.Campaign_Name__c='MyCampaign';
     		   reco.Status__c = 'In Progress';
     	insert reco;
        ApexPages.StandardController sc = new ApexPages.standardController(reco);
     	DndCampaignController controller = new DndCampaignController(sc);
    }
    
	@isTest static void PartyPageTest(){
        DndCampaignController s = new DndCampaignController();
        PageReference pg = s.GoToParty();
        system.assertEquals('/apex/partyPage', pg.getUrl());
        system.assertEquals(true, pg.getRedirect());
        system.assertEquals(new Map < String, String >(), pg.getParameters());
        system.assertEquals(new Map < String, String >(), pg.getHeaders());
    }
   

}